-- Run this entire script in the Supabase SQL Editor to set up your database completely.

BEGIN;

-- 1. Create the 'settings' table
-- This stores the global application status (open, closed, closing-soon)
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- 2. Create the 'submissions' table
-- This stores all the job applications received
CREATE TABLE IF NOT EXISTS public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    data JSONB NOT NULL
);

-- 3. Insert default application status
-- This ensures the app has a status to read when it first starts
INSERT INTO public.settings (key, value)
VALUES ('appStatus', 'open')
ON CONFLICT (key) DO NOTHING;

-- 4. Enable Row Level Security (RLS)
-- This is required for Supabase security policies to work
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

-- 5. Create Access Policies
-- We drop existing policies first to prevent errors if you run this script multiple times.

-- Settings Policies
DROP POLICY IF EXISTS "Public Read Settings" ON public.settings;
CREATE POLICY "Public Read Settings" ON public.settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Update Settings" ON public.settings;
CREATE POLICY "Public Update Settings" ON public.settings FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Insert Settings" ON public.settings;
CREATE POLICY "Public Insert Settings" ON public.settings FOR INSERT WITH CHECK (true);

-- Submissions Policies
DROP POLICY IF EXISTS "Public Insert Submissions" ON public.submissions;
CREATE POLICY "Public Insert Submissions" ON public.submissions FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read Submissions" ON public.submissions;
CREATE POLICY "Public Read Submissions" ON public.submissions FOR SELECT USING (true);

COMMIT;
